title: Nodetomic
description: Nodetomic documentation
baseurl: '/nodetomic' # the subpath of your site, e.g. /blog
url: 'https://kevoj.github.io'
remote_theme: pmarsceill/just-the-docs
color_scheme: node
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - setup.md
  - scripts.md
  - api.md
  - swagger.md
  - aws.md
  - fcm.md
aux_links:
  'Nodetomic on GitHub':
    - '//github.com/kevoj/nodetomic'
