title: Nodetomic
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - setup.md
  - scripts.md
  - api.md
  - swagger.md
  - aws.md
  - fcm.md