title: Nodetomic
description: Nodetomic documentation
baseurl: '/nodetomic' # the subpath of your site, e.g. /blog
url: 'https://kevoj.github.io'
remote_theme: pmarsceill/just-the-docs
color_scheme: light
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
aux_links:
  'Nodetomic on GitHub':
    - '//github.com/kevoj/nodetomic'
